name: nourgomla
description: E-commerce Application


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.3.4
  #flutter_form_builder: ^4.2.0
  cupertino_icons: ^1.0.0
  cached_network_image: ^2.5.0
  json_annotation: ^3.1.1
  http: ^0.12.2
  get: ^3.26.0
  carousel_slider: ^3.0.0
  carousel_pro: ^1.0.0
  photo_view: ^0.10.3
  international_phone_input: ^1.0.4
  pagination_view: ^1.0.4
  animated_splash_screen: ^1.0.1+2
  flutter_spinkit: ^4.1.1
  get_storage: ^1.3.2
  image_picker: ^0.6.7+22
  geolocator: ^6.2.1
  geocoder: ^0.2.1
  sqflite: ^1.3.2+4
  hexcolor: ^2.0.0
  provider: ^4.3.3
  google_maps_flutter: ^1.2.0
  material_design_icons_flutter: ^4.0.5855
  rounded_loading_button: ^1.0.18
  flutter_barcode_scanner: ^1.0.2
  dio: ^3.0.10
  animated_widgets: ^1.0.6
  animated_text_kit: ^3.1.2
  blinking_text: ^0.0.4+1

  google_api_headers: ">=0.1.0 <1.0.0"
  google_maps_webservice: ^0.0.19
  tuple: ^1.0.3
  permission_handler: ^5.0.1+1
  geodesy: ^0.3.2
  connectivity: ^2.0.2
#  device_preview: ^0.5.5

  firebase_auth: ^0.18.1
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^4.0.1
  firebase_messaging: ^7.0.3
  flutter_rating_bar: ^3.2.0+1
  firebase_dynamic_links: ^0.6.3
  flutter_share: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/


  fonts:
    - family: Rakkas
      fonts:
        - asset: assets/Rakkas.ttf
